server:
  port: 80
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册eureka server默认为true
    fetchRegistry: true   #是否从eureka server抓取已有的注册信息，默认为true  单节点必须设置为true才能配合ribbon使用负载均衡
    service-url:
     # defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  #集群
      defaultZone: http://eureka7001.com:7001/eureka   #单机

