server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端实例名称
  client:
    register-with-eureka: false   #表示eureka不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，维护服务实例，不检索服务
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka/   #集群指向其他eureka多个用逗号分隔
      defaultZone: http://eureka7001.com:7001/eureka/   #单机指向就是指向自己
